### ISSUE TITLE
一个不知道是不是bug的bug...

### ISSUE THREAD

**Issue by Zephylaci** [YKilin/nhentai-resolution#1]
没试用ajax会啥结果..
http://localhost:8888/?url=https://nhentai.net/language/chinese/
这样直接丢浏览器里，丢两次第二次会读取两组一样的结果..
三次三组..以此类推...

**Comment by Zephylaci** [comment]
啊，对了，单个的不会有这问题....
我试着在你的这个函数外面套了个koa..用ajax调用...可能也有我重构了的原因吧...
有的时候会读不出来东西，多次读取几乎一定会出错...成功率大约三分之一吧...错误处理弄的我很烦恼...
猛然意识到...这不是用socket的好机会么...

**Comment by Tsuk1ko** [comment]
感谢您的反馈！已经修复了这个问题

实际上是我定义了返回结果这个全局变量的问题，改为局部变量就可以了

还有另一个问题是，不知道为何nodejs通过`https`模块进行请求的时候，第一次会正常，第二次总会没有结果，第三次又正常，以此类推，因此目前使用了重试次数来解决这个问题

如果您对这个问题有什么看法请务必再提一下issue√
