### ISSUE TITLE
这次我是来请教的..

### ISSUE THREAD

**Issue by Zephylaci** [YKilin/nhentai-resolution#3]
首先列表页的读取问题，感觉上似乎是读取到所有url然后再去一个页面一个页面读取...并发控制似乎是一次只读取一个？不晓得我是否理解有误？没细看..
然后这个注释风格..我不相信是自己一点点改成这个格式的..用的什么插件呀？
顺便膜拜下大佬..没两天就写的像模像样了...想想自己要到这个地步估计代码得重构两三会才能有这样的完成度..不经流下悔恨的泪水..

**Comment by Tsuk1ko** [comment]
是的，是先取得所有URL再一个个页面读取，没有设计并发访问。
首先是因为考虑到如果多人使用的情况下实际上就已经是并发了，如果自己再去并发可能反而会网络爆炸什么的……并且一个个来的速度也并不慢，如果是美国本地的服务器（因为nhentai套了cloudflare，相当于服务器也在美国）只需要10秒就可以解析完一页的25本，国内就慢一点要30秒。
其次是批量下载一般也不止会下一页，实际上就可以同时解析多页手动并发了。
然后可能是我太懒所以没去研究多线程什么的……不知道node有没有类似编程中信号量这样的东西，不然不太好控制，不知道什么时候所有访问都完成，还涉及到共享变量读写问题

至于注释什么的……我也是最近才开始用VS Code，发现是真的好用，插件很齐全，你看到的注释，代码格式化，都是插件功能，我以前很懒就没去弄这些，现在才发现本地开发是真的爽23333（我以前写代码都是直接用Kodexplorer在VPS上现场写现场跑

其实是上周周末参加学校实训，因为内容很枯燥所以耐不住寂寞就把nodejs又研究了一下就重写了_(:3」∠)_

**Comment by Zephylaci** [comment]
啊..本地么..我虽然也用过VS CODE不过还真是没有注意插件这一块...学生时代就是好呀..大把的时间..
现在白天上班虽然不忙..但是公司只能远程指定的机器通过远程来的浏览器上网..自己干事情非常麻烦...而且响应速度甚至不如手机..
node信号量..似乎是没有的..最多就是promise有个状态..出现的时候必定是结束了...其它子进程也有结束状态都可以拿来做并发控制..再不行写个数组push进去几个..长度大于一定值不push不够了补..运行结束了再取出来也是个方法...嘛..比较粗糙就是了..
顺便想问下，linux下守护进程有什么好法子么..我在家拿树莓派SSH反向代理到阿里云上..从公司用能上网的浏览器控制..总是不知道什么时候就断了..nhoup..感觉不出来有没有用.....最后用pm2 控制node不断的调autossh脚本来保持链接...感觉好傻...

**Comment by Tsuk1ko** [comment]
supervisor，很有名的守护程序，配置也很简单

**Comment by Zephylaci** [comment]
恩..先记个关键字...pm2先凑合着用..没事干的时候还能写个前端页面给它..对了..大佬，知道什么能在浏览器里运行的shell么..阿里云里有一个但是非常的卡...或者有没有什么库把shell的内容丢到网页里来的那种？

**Comment by Tsuk1ko** [comment]
https://github.com/shellinabox/shellinabox
这个挺不错的，而且UI跟普通ssh客户端几乎一模一样

**Comment by Zephylaci** [comment]
哎呀呀，有大佬带就是事半功倍,,,
那我再问两个..比如经常在一些网站上看到类似嵌在网页里IDE那种风格的编辑器..比如慕课网还有各种外国网站..有的能即时展示..还能测试下JS啥的..这种的有库么..
再一个..关于文件系统的..就类似于你博客里那个h5al..这个有类似功能..Node版本的么..
嘛，总之先谢过..研究下那个shell去..争取明天在公司能用上...

**Comment by Tsuk1ko** [comment]
这两个我就不知道了_(:3」∠)_

**Comment by Zephylaci** [comment]
这..shell我用上了..体验真好...剩下就是编辑器和文件系统了..找到个差不多的改一个也是事....慢慢找了..可惜用不惯vim...也没好用的配置...

**Comment by Tsuk1ko** [comment]
shell下的编辑器我最喜欢nano，贴合windows的使用习惯……vi系列那种编辑方式我一直觉得挺反人类的……

**Comment by Zephylaci** [comment]
vim esc 后出类似命令行的东西..习惯了的话效率应该是不错的..然而不习惯.查找啥的也是..不知道怎么停在那..下了个配置文件..配出了侧边的文件树..还是不怎么好用就是了....大佬有nano的配置文件么！一键导入的那种...

**Comment by Tsuk1ko** [comment]
呃，我也不用配置文件，nano直接`apt-get` `yum`装了就用啊，不用怎么配置

**Comment by Zephylaci** [comment]
我用上nano了..但是...include 代码高亮设置里..HTML CSS都有，但是没有JS？..我该去哪里获得额外的代码高亮插件？

**Comment by Zephylaci** [comment]
顺便问下 shellinabox  要怎么切换背景颜色...我开了代码高亮反而看不清了..因为背景是白的

**Comment by Zephylaci** [comment]
我顺便在来自问自答一波..在线IDE..我刚发现..coding的在线IDE是开源的..
文件系统..我现在在用stbui-ide这个..不知道为啥没人关注..但是基本功能都有..改一改还是蛮好用的..
下面就是笔记程序.. 现在在用在线的印象笔记..gitHub上有API，套个壳子..整合一套就是个很好用的基于网页的开发环境了..想想还是蛮激动的..

**Comment by Tsuk1ko** [comment]
不用nano写代码……不清楚
shellinabox我只是知道，没实际用过，你看能不能改css之类的吧
我曾经也是在线党，但是发现还是本地好用23333

**Comment by Zephylaci** [comment]
我当然知道本地好用..然而我现在没法跑本地...CSS我试过了..太麻烦了...最后打算还是用Coding的IDE随便结合一个Git库来干这个事情..猛然发现用coding的话，还送个测试服务器...完全没必要自己搭..也许可以试试萌化..只可惜..没有那个审美....再看了..
